version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - .env:/app/.env
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    env_file: .env

  mysql:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file: .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 25
      interval: 5s
volumes:
  mysql_data:
